In [37]:
#Write a Python Program to Add Two Matrices?

M1 = np.matrix([1,2,3,4,5])
M2 = np.matrix([3,4,5,6,7]).T
M1+M2





matrix([[ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12]])

In [38]:
#Write a Python Program to Multiply Two Matrices?
np.dot(M1,M2)

matrix([[85]])

In [39]:
#Write a Python Program to Transpose a Matrix?
np.matrix([1,2,3,4]).T


matrix([[1],
        [2],
        [3],
        [4]])

In [41]:
#Write a Python Program to Sort Words in Alphabetic Order?
l = ['Shabdali','Aditya','Rutuja','Alifa','Pranita','Shubhangi','Shardul']
l.sort()
l

['Aditya', 'Alifa', 'Pranita', 'Rutuja', 'Shabdali', 'Shardul', 'Shubhangi']

In [42]:
#Write a Python Program to Remove Punctuation From a String?
s = 'Shabdali!Deshapnde'
s.replace('!', " ")

'Shabdali Deshapnde'